-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 20:48:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Borrower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Borrower` (
  `borrowerID` BIGINT(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `phone_number` VARCHAR(10) NULL,
  `date_of_birth` VARCHAR(100) NOT NULL,
  `credit_score` BIGINT(20) NOT NULL,
  `User_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`borrowerID`, `User_ID`),
  INDEX `fk_Borrower_User_idx` (`User_ID` ASC),
  CONSTRAINT `fk_Borrower_User`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LoanApplication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LoanApplication` (
  `applicationID` BIGINT(20) NOT NULL,
  `loan_amount` VARCHAR(100) NOT NULL,
  `street_address` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `zipcode` VARCHAR(100) NOT NULL,
  `User_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`applicationID`, `User_ID`),
  INDEX `fk_LoanApplication_User1_idx` (`User_ID` ASC),
  CONSTRAINT `fk_LoanApplication_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Borrower_has_LoanApplication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Borrower_has_LoanApplication` (
  `Borrower_borrowerID` BIGINT(20) NOT NULL,
  `Borrower_User_ID` BIGINT(20) NOT NULL,
  `LoanApplication_applicationID` BIGINT(20) NOT NULL,
  `LoanApplication_User_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`Borrower_borrowerID`, `Borrower_User_ID`, `LoanApplication_applicationID`, `LoanApplication_User_ID`),
  INDEX `fk_Borrower_has_LoanApplication_LoanApplication1_idx` (`LoanApplication_applicationID` ASC, `LoanApplication_User_ID` ASC),
  INDEX `fk_Borrower_has_LoanApplication_Borrower1_idx` (`Borrower_borrowerID` ASC, `Borrower_User_ID` ASC),
  CONSTRAINT `fk_Borrower_has_LoanApplication_Borrower1`
    FOREIGN KEY (`Borrower_borrowerID` , `Borrower_User_ID`)
    REFERENCES `mydb`.`Borrower` (`borrowerID` , `User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Borrower_has_LoanApplication_LoanApplication1`
    FOREIGN KEY (`LoanApplication_applicationID` , `LoanApplication_User_ID`)
    REFERENCES `mydb`.`LoanApplication` (`applicationID` , `User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Debts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Debts` (
  `account_number` INT NOT NULL,
  `creditor` VARCHAR(100) NOT NULL,
  `balance` DECIMAL(2) NOT NULL,
  `past_due` DECIMAL(2) NOT NULL,
  `date_open` DATE NOT NULL,
  `Borrower_borrowerID` BIGINT(20) NOT NULL,
  `Borrower_User_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`account_number`, `Borrower_borrowerID`, `Borrower_User_ID`),
  INDEX `fk_Debts_Borrower1_idx` (`Borrower_borrowerID` ASC, `Borrower_User_ID` ASC),
  CONSTRAINT `fk_Debts_Borrower1`
    FOREIGN KEY (`Borrower_borrowerID` , `Borrower_User_ID`)
    REFERENCES `mydb`.`Borrower` (`borrowerID` , `User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
